version: '3'
services:
  node-express-app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - node-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  node-network:
    driver: bridge